//! Purpose:
//! Emits the `__rt_random_u32`, `__rt_random_u32_linux_ok` runtime helper assembly for random u32.
//! Keeps PHP array/hash storage, heap ownership, and target-specific ABI variants in one focused emitter.
//!
//! Called from:
//! - `crate::codegen::runtime::emitters::emit_runtime()` via `crate::codegen::runtime::arrays`.
//!
//! Key details:
//! - Random helpers produce bounded integer values used by array_rand and shuffle without modulo bias where possible.

use crate::codegen::emit::Emitter;
use crate::codegen::platform::Arch;
use crate::codegen::platform::Platform;

/// Emits the `__rt_random_u32` runtime helper.
///
/// Dispatches to `emit_random_u32_linux_x86_64` on x86_64 Linux; otherwise emits
/// macOS or Linux ARM64 variants. On macOS this calls `arc4random()` from libc.
/// On Linux ARM64 it attempts the `getrandom` syscall first; if that fails
/// (e.g., `/dev/urandom` not yet seeded) it falls back to `time()` mixed into a 32-bit value.
///
/// The result is returned in the platform's integer register: `x0` on ARM64, `eax` on x86_64.
pub fn emit_random_u32(emitter: &mut Emitter) {
    if emitter.target.arch == Arch::X86_64 {
        emit_random_u32_linux_x86_64(emitter);
        return;
    }

    emitter.blank();
    emitter.comment("--- runtime: random_u32 ---");
    emitter.label_global("__rt_random_u32");

    match emitter.platform {
        Platform::MacOS => {
            emitter.instruction("sub sp, sp, #16");                             // reserve a tiny frame so the nested libc call can preserve our return address
            emitter.instruction("str x30, [sp, #0]");                           // save the caller's return address before bl clobbers x30
            emitter.bl_c("arc4random");                                         // use libc's arc4random() on macOS
            emitter.instruction("mov w0, w0");                                  // zero-extend the uint32 result into x0
            emitter.instruction("ldr x30, [sp, #0]");                           // restore the caller's return address after the libc call returns
            emitter.instruction("add sp, sp, #16");                             // release the temporary frame
            emitter.instruction("ret");                                         // return the random uint32
        }
        Platform::Linux => {
            emitter.instruction("sub sp, sp, #32");                             // allocate stack space for the syscall buffer and saved frame
            emitter.instruction("stp x29, x30, [sp, #16]");                     // save frame pointer and return address
            emitter.instruction("add x29, sp, #16");                            // set up a frame pointer for the fallback path

            emitter.instruction("mov x0, sp");                                  // buffer = stack scratch space
            emitter.instruction("mov x1, #4");                                  // request 4 random bytes
            emitter.instruction("mov x2, #0");                                  // flags = 0
            emitter.instruction("mov x8, #278");                                // Linux aarch64 getrandom syscall number
            emitter.instruction("svc #0");                                      // ask the kernel for random bytes
            emitter.instruction("cmp x0, #4");                                  // did getrandom fill the full uint32 buffer?
            emitter.instruction("b.eq __rt_random_u32_linux_ok");               // yes — use the kernel-generated bytes

            // -- fallback: mix time(NULL) into a 32-bit value if getrandom is unavailable --
            emitter.instruction("mov x0, #0");                                  // pass NULL to time() to request only the return value
            emitter.bl_c("time");                                               // get coarse wall-clock seconds from libc
            emitter.instruction("mov x9, x0");                                  // preserve the low half for mixing
            emitter.instruction("lsl x0, x0, #32");                             // move the timestamp into the high half
            emitter.instruction("eor x0, x0, x9");                              // fold high and low halves together into one word
            emitter.instruction("b __rt_random_u32_linux_done");                // skip loading the syscall buffer

            emitter.label("__rt_random_u32_linux_ok");
            emitter.instruction("ldr w0, [sp, #0]");                            // load the generated uint32 from the stack buffer

            emitter.label("__rt_random_u32_linux_done");
            emitter.instruction("ldp x29, x30, [sp, #16]");                     // restore frame pointer and return address
            emitter.instruction("add sp, sp, #32");                             // release the temporary stack frame
            emitter.instruction("ret");                                         // return the random uint32
        }
        Platform::Web => {
            panic!("native random_u32 runtime emission is not available for wasm32-web");
        }
    }
}

/// Emits the `__rt_random_u32` runtime helper for Linux x86_64.
///
/// Attempts the `getrandom` syscall first; if it fails (e.g., `/dev/urandom` not yet
/// seeded) it falls back to `time()` mixed into a 32-bit value. The result is returned
/// in `eax`.
fn emit_random_u32_linux_x86_64(emitter: &mut Emitter) {
    emitter.blank();
    emitter.comment("--- runtime: random_u32 ---");
    emitter.label_global("__rt_random_u32");

    emitter.instruction("push rbp");                                            // preserve the caller frame pointer before reserving x86_64 random scratch space
    emitter.instruction("mov rbp, rsp");                                        // establish a stable frame base for the getrandom scratch buffer and fallback path
    emitter.instruction("sub rsp, 16");                                         // reserve aligned stack space for a 4-byte random buffer while keeping the fallback libc call aligned
    emitter.instruction("lea rdi, [rbp - 4]");                                  // pass a stack scratch buffer to the Linux x86_64 getrandom syscall
    emitter.instruction("mov rsi, 4");                                          // request exactly four random bytes so the result fits in one uint32 slot
    emitter.instruction("xor edx, edx");                                        // request the default blocking getrandom behavior without extra flags
    emitter.instruction("mov eax, 318");                                        // Linux x86_64 syscall 318 = getrandom
    emitter.instruction("syscall");                                             // ask the Linux kernel for four random bytes
    emitter.instruction("cmp rax, 4");                                          // check whether the kernel filled the full uint32 scratch buffer
    emitter.instruction("je __rt_random_u32_linux_ok_x86");                     // use the kernel-generated bytes when getrandom succeeded
    emitter.instruction("xor edi, edi");                                        // pass NULL to time() so the fallback only returns the current timestamp
    emitter.instruction("call time");                                           // fetch coarse wall-clock seconds as a deterministic fallback when getrandom is unavailable
    emitter.instruction("mov rcx, rax");                                        // preserve the low half of the fallback timestamp before mixing it into one uint32 word
    emitter.instruction("shl rax, 32");                                         // move the fallback timestamp into the high half so both halves contribute to the mixed fallback value
    emitter.instruction("xor rax, rcx");                                        // fold the high and low halves together into one pseudo-randomish uint32 candidate
    emitter.instruction("jmp __rt_random_u32_linux_done_x86");                  // skip loading the getrandom scratch buffer on the fallback path

    emitter.label("__rt_random_u32_linux_ok_x86");
    emitter.instruction("mov eax, DWORD PTR [rbp - 4]");                        // load the generated uint32 from the getrandom scratch buffer into the x86_64 integer result register

    emitter.label("__rt_random_u32_linux_done_x86");
    emitter.instruction("add rsp, 16");                                         // release the x86_64 random scratch buffer before returning to the caller
    emitter.instruction("pop rbp");                                             // restore the caller frame pointer after the x86_64 random helper completes
    emitter.instruction("ret");                                                 // return the generated uint32 in eax
}
