//! Purpose:
//! Collects wasm32-web local metadata from nested statement bodies.
//! Keeps recursive statement walking out of the local metadata dispatcher.
//!
//! Called from:
//! - `super::collect_stmt_locals()` for if/loop/for/switch/body recursion.
//!
//! Key details:
//! - Delegates each nested statement back to the parent dispatcher so assignment,
//!   foreach, and mutation metadata keep their existing lowering behavior.

use super::*;

pub(super) fn collect_if_locals(
    then_body: &[Stmt],
    elseif_clauses: &[(Expr, Vec<Stmt>)],
    else_body: Option<&[Stmt]>,
    locals: &mut HashMap<String, LocalKind>,
    array_value_kinds: &mut HashMap<String, Vec<ValueCellKind>>,
    array_runtime_value_kinds: &mut HashMap<String, ValueCellKind>,
    array_nested_values: &mut HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    array_runtime_nested_values: &mut HashMap<String, NestedArrayMetadata>,
    array_key_kinds: &mut HashMap<String, Vec<AssocKeyKind>>,
    array_key_values: &mut HashMap<String, Vec<AssocKeyValue>>,
    php_normalized_key_arrays: &mut HashSet<String>,
    callable_targets: &mut HashMap<String, String>,
    string_static_values: &mut HashMap<String, String>,
    function_return_kinds: &HashMap<String, ValueKind>,
    function_callable_return_targets: &HashMap<String, String>,
    function_possible_callable_return_targets: &HashMap<String, Vec<String>>,
    function_static_string_returns: &HashMap<String, String>,
    function_possible_static_string_returns: &HashMap<String, Vec<String>>,
    function_array_return_value_kinds: &HashMap<String, Vec<ValueCellKind>>,
    function_array_return_runtime_value_kinds: &HashMap<String, ValueCellKind>,
    function_array_return_layouts: &HashMap<String, ArrayLayout>,
    function_array_return_nested_values: &HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    function_array_return_key_kinds: &HashMap<String, Vec<AssocKeyKind>>,
    function_array_return_key_values: &HashMap<String, Vec<AssocKeyValue>>,
    function_array_return_param_indices: &HashMap<String, usize>,
    object_classes: &HashMap<String, object_metadata::ObjectClassInfo>,
    constants: &HashMap<String, ConstantValue>,
    class_constants: &HashMap<String, ConstantValue>,
    array_constants: &HashMap<String, ConstantArrayValue>,
) {
    collect_stmt_body_locals(
        then_body,
        locals,
        array_value_kinds,
        array_runtime_value_kinds,
        array_nested_values,
        array_runtime_nested_values,
        array_key_kinds,
        array_key_values,
        php_normalized_key_arrays,
        callable_targets,
        string_static_values,
        function_return_kinds,
        function_callable_return_targets,
        function_possible_callable_return_targets,
        function_static_string_returns,
        function_possible_static_string_returns,
        function_array_return_value_kinds,
        function_array_return_runtime_value_kinds,
        function_array_return_layouts,
        function_array_return_nested_values,
        function_array_return_key_kinds,
        function_array_return_key_values,
        function_array_return_param_indices,
        object_classes,
        constants,
        class_constants,
        array_constants,
    );
    for (_, body) in elseif_clauses {
        collect_stmt_body_locals(
            body,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
    if let Some(else_body) = else_body {
        collect_stmt_body_locals(
            else_body,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
}

pub(super) fn collect_for_locals(
    init: Option<&Stmt>,
    body: &[Stmt],
    update: Option<&Stmt>,
    locals: &mut HashMap<String, LocalKind>,
    array_value_kinds: &mut HashMap<String, Vec<ValueCellKind>>,
    array_runtime_value_kinds: &mut HashMap<String, ValueCellKind>,
    array_nested_values: &mut HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    array_runtime_nested_values: &mut HashMap<String, NestedArrayMetadata>,
    array_key_kinds: &mut HashMap<String, Vec<AssocKeyKind>>,
    array_key_values: &mut HashMap<String, Vec<AssocKeyValue>>,
    php_normalized_key_arrays: &mut HashSet<String>,
    callable_targets: &mut HashMap<String, String>,
    string_static_values: &mut HashMap<String, String>,
    function_return_kinds: &HashMap<String, ValueKind>,
    function_callable_return_targets: &HashMap<String, String>,
    function_possible_callable_return_targets: &HashMap<String, Vec<String>>,
    function_static_string_returns: &HashMap<String, String>,
    function_possible_static_string_returns: &HashMap<String, Vec<String>>,
    function_array_return_value_kinds: &HashMap<String, Vec<ValueCellKind>>,
    function_array_return_runtime_value_kinds: &HashMap<String, ValueCellKind>,
    function_array_return_layouts: &HashMap<String, ArrayLayout>,
    function_array_return_nested_values: &HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    function_array_return_key_kinds: &HashMap<String, Vec<AssocKeyKind>>,
    function_array_return_key_values: &HashMap<String, Vec<AssocKeyValue>>,
    function_array_return_param_indices: &HashMap<String, usize>,
    object_classes: &HashMap<String, object_metadata::ObjectClassInfo>,
    constants: &HashMap<String, ConstantValue>,
    class_constants: &HashMap<String, ConstantValue>,
    array_constants: &HashMap<String, ConstantArrayValue>,
) {
    if let Some(init) = init {
        super::collect_stmt_locals(
            init,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
    collect_stmt_body_locals(
        body,
        locals,
        array_value_kinds,
        array_runtime_value_kinds,
        array_nested_values,
        array_runtime_nested_values,
        array_key_kinds,
        array_key_values,
        php_normalized_key_arrays,
        callable_targets,
        string_static_values,
        function_return_kinds,
        function_callable_return_targets,
        function_possible_callable_return_targets,
        function_static_string_returns,
        function_possible_static_string_returns,
        function_array_return_value_kinds,
        function_array_return_runtime_value_kinds,
        function_array_return_layouts,
        function_array_return_nested_values,
        function_array_return_key_kinds,
        function_array_return_key_values,
        function_array_return_param_indices,
        object_classes,
        constants,
        class_constants,
        array_constants,
    );
    if let Some(update) = update {
        super::collect_stmt_locals(
            update,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
}

pub(super) fn collect_switch_locals(
    cases: &[(Vec<Expr>, Vec<Stmt>)],
    default: Option<&[Stmt]>,
    locals: &mut HashMap<String, LocalKind>,
    array_value_kinds: &mut HashMap<String, Vec<ValueCellKind>>,
    array_runtime_value_kinds: &mut HashMap<String, ValueCellKind>,
    array_nested_values: &mut HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    array_runtime_nested_values: &mut HashMap<String, NestedArrayMetadata>,
    array_key_kinds: &mut HashMap<String, Vec<AssocKeyKind>>,
    array_key_values: &mut HashMap<String, Vec<AssocKeyValue>>,
    php_normalized_key_arrays: &mut HashSet<String>,
    callable_targets: &mut HashMap<String, String>,
    string_static_values: &mut HashMap<String, String>,
    function_return_kinds: &HashMap<String, ValueKind>,
    function_callable_return_targets: &HashMap<String, String>,
    function_possible_callable_return_targets: &HashMap<String, Vec<String>>,
    function_static_string_returns: &HashMap<String, String>,
    function_possible_static_string_returns: &HashMap<String, Vec<String>>,
    function_array_return_value_kinds: &HashMap<String, Vec<ValueCellKind>>,
    function_array_return_runtime_value_kinds: &HashMap<String, ValueCellKind>,
    function_array_return_layouts: &HashMap<String, ArrayLayout>,
    function_array_return_nested_values: &HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    function_array_return_key_kinds: &HashMap<String, Vec<AssocKeyKind>>,
    function_array_return_key_values: &HashMap<String, Vec<AssocKeyValue>>,
    function_array_return_param_indices: &HashMap<String, usize>,
    object_classes: &HashMap<String, object_metadata::ObjectClassInfo>,
    constants: &HashMap<String, ConstantValue>,
    class_constants: &HashMap<String, ConstantValue>,
    array_constants: &HashMap<String, ConstantArrayValue>,
) {
    for (_, body) in cases {
        collect_stmt_body_locals(
            body,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
    if let Some(default) = default {
        collect_stmt_body_locals(
            default,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
}

pub(super) fn collect_stmt_body_locals(
    body: &[Stmt],
    locals: &mut HashMap<String, LocalKind>,
    array_value_kinds: &mut HashMap<String, Vec<ValueCellKind>>,
    array_runtime_value_kinds: &mut HashMap<String, ValueCellKind>,
    array_nested_values: &mut HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    array_runtime_nested_values: &mut HashMap<String, NestedArrayMetadata>,
    array_key_kinds: &mut HashMap<String, Vec<AssocKeyKind>>,
    array_key_values: &mut HashMap<String, Vec<AssocKeyValue>>,
    php_normalized_key_arrays: &mut HashSet<String>,
    callable_targets: &mut HashMap<String, String>,
    string_static_values: &mut HashMap<String, String>,
    function_return_kinds: &HashMap<String, ValueKind>,
    function_callable_return_targets: &HashMap<String, String>,
    function_possible_callable_return_targets: &HashMap<String, Vec<String>>,
    function_static_string_returns: &HashMap<String, String>,
    function_possible_static_string_returns: &HashMap<String, Vec<String>>,
    function_array_return_value_kinds: &HashMap<String, Vec<ValueCellKind>>,
    function_array_return_runtime_value_kinds: &HashMap<String, ValueCellKind>,
    function_array_return_layouts: &HashMap<String, ArrayLayout>,
    function_array_return_nested_values: &HashMap<String, Vec<Option<NestedArrayMetadata>>>,
    function_array_return_key_kinds: &HashMap<String, Vec<AssocKeyKind>>,
    function_array_return_key_values: &HashMap<String, Vec<AssocKeyValue>>,
    function_array_return_param_indices: &HashMap<String, usize>,
    object_classes: &HashMap<String, object_metadata::ObjectClassInfo>,
    constants: &HashMap<String, ConstantValue>,
    class_constants: &HashMap<String, ConstantValue>,
    array_constants: &HashMap<String, ConstantArrayValue>,
) {
    for stmt in body {
        super::collect_stmt_locals(
            stmt,
            locals,
            array_value_kinds,
            array_runtime_value_kinds,
            array_nested_values,
            array_runtime_nested_values,
            array_key_kinds,
            array_key_values,
            php_normalized_key_arrays,
            callable_targets,
            string_static_values,
            function_return_kinds,
            function_callable_return_targets,
            function_possible_callable_return_targets,
            function_static_string_returns,
            function_possible_static_string_returns,
            function_array_return_value_kinds,
            function_array_return_runtime_value_kinds,
            function_array_return_layouts,
            function_array_return_nested_values,
            function_array_return_key_kinds,
            function_array_return_key_values,
            function_array_return_param_indices,
            object_classes,
            constants,
            class_constants,
            array_constants,
        );
    }
}
